[tools]
actionlint = "1.7.12"
go = "1.26.4"
lua = "5.5.0"
lua-language-server = "3.18.2"
luajit = "2.1.1744318430"
node = "26.4.0"
neovim = "0.12.3"
just = "1.54.0"
golangci-lint = "2.12.2"
gofumpt = "0.10.0"
markdownlint-cli2 = "0.22.1"
"npm:prettier" = "3.8.4"
"npm:renovate" = "43.243.2"
stylua = "2.5.2"
swiftformat = "0.61.1"
swiftlint = "0.64.1"
