name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Ensure package dependencies
        run: just ensure-deps

      - name: Run checks
        run: just check
